const menu_food = [
  { menu: "오리지널 휘낭시에", url: "../image/menu_food/menu_food(1).jpg" },
  { menu: "얼그레이 휘낭시에", url: "../image/menu_food/menu_food(2).jpg" },
  {
    menu: "상하농원에그촉촉카스텔라(2P)",
    url: "../image/menu_food/menu_food(3).jpg",
  },
  {
    menu: "상하농원에그촉촉카스텔라(W)",
    url: "../image/menu_food/menu_food(4).jpg",
  },
  { menu: "대파베이컨 크림치즈", url: "../image/menu_food/menu_food(5).jpg" },
  { menu: "무화과월넛 크림치즈", url: "../image/menu_food/menu_food(6).jpg" },
  { menu: "허니&카이막 크림치즈", url: "../image/menu_food/menu_food(7).jpg" },
  {
    menu: "초당옥수수 바스크 치즈 케이크(조각)",
    url: "../image/menu_food/menu_food(8).jpg",
  },
  {
    menu: "딸기 생크림 케이크(조각)",
    url: "../image/menu_food/menu_food(9).jpg",
  },
  { menu: "티라미수", url: "../image/menu_food/menu_food(10).jpg" },
  {
    menu: "피스타치오 라즈베리 케이크",
    url: "../image/menu_food/menu_food(11).jpg",
  },
  { menu: "플레인 베이글", url: "../image/menu_food/menu_food(12).jpg" },
  { menu: "블루베리 베이글", url: "../image/menu_food/menu_food(13).jpg" },
  { menu: "까눌레", url: "../image/menu_food/menu_food(14).jpg" },
  { menu: "크루아상", url: "../image/menu_food/menu_food(15).jpg" },
  { menu: "우유크림 랑드샤", url: "../image/menu_food/menu_food(16).jpg" },
  { menu: "토피넛 다크 초콜릿", url: "../image/menu_food/menu_food(17).jpg" },
  { menu: "플로랑탱", url: "../image/menu_food/menu_food(18).jpg" },
  { menu: "에그샐러드 샌드위치", url: "../image/menu_food/menu_food(19).jpg" },
  { menu: "BELT 샌드위치", url: "../image/menu_food/menu_food(20).jpg" },
  { menu: "햄에그 잉글리시머핀", url: "../image/menu_food/menu_food(21).jpg" },
  {
    menu: "베이컨에그 잉글리시머핀",
    url: "../image/menu_food/menu_food(22).jpg",
  },
  { menu: "맛있는영양반숙란", url: "../image/menu_food/menu_food(23).jpg" },
  { menu: "나타 초콜릿", url: "../image/menu_food/menu_food(24).jpg" },
  { menu: "나타 애플", url: "../image/menu_food/menu_food(25).jpg" },
  { menu: "나타 오리지널", url: "../image/menu_food/menu_food(26).jpg" },
  { menu: "피칸파이", url: "../image/menu_food/menu_food(27).jpg" },
  { menu: "다크 헤이즐넛 케이크", url: "../image/menu_food/menu_food(28).jpg" },
  { menu: "바스크 치즈 케이크", url: "../image/menu_food/menu_food(29).jpg" },
  { menu: "우유크림 롤", url: "../image/menu_food/menu_food(30).jpg" },
  { menu: "우유크림 롤(홀)", url: "../image/menu_food/menu_food(31).jpg" },
  { menu: "생크림 소프트 케이크", url: "../image/menu_food/menu_food(32).jpg" },
  { menu: "오트 크림롤", url: "../image/menu_food/menu_food(33).jpg" },
  { menu: "볼로네제 스파게티", url: "../image/menu_food/menu_food(34).jpg" },
  { menu: "시저 샐러드", url: "../image/menu_food/menu_food(35).jpg" },
  { menu: "IL FORNO 라자냐", url: "../image/menu_food/menu_food(36).jpg" },
  { menu: "마르게리타", url: "../image/menu_food/menu_food(37).jpg" },
  { menu: "D.O.C", url: "../image/menu_food/menu_food(38).jpg" },
  { menu: "디아볼라", url: "../image/menu_food/menu_food(39).jpg" },
  {
    menu: "머쉬룸 크림오븐 스파게티",
    url: "../image/menu_food/menu_food(40).jpg",
  },
  { menu: "그리시니", url: "../image/menu_food/menu_food(41).jpg" },
];
